apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32123
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus
  sessionAffinity: None
  type: LoadBalancer
