apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  # service type should be either NodePort to expose on local node or LoadBalancer if working with a cloud provider
  type: ((SVC_TYPE))
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus
