# prometheus server
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: ((NAMESPACE))
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: ((NAMESPACE))
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      scraper: prometheus
  resources:
    requests:
      memory: 400Mi
